export const penangLocations = [
  "Air Itam",
  "Balik Pulau",
  "Batu Ferringhi",
  "Batu Lanchang",
  "Batu Maung",
  "Bayan Baru",
  "Bayan Lepas",
  "Bertam",
  "Bukit Jambul",
  "Bukit Mertajam",
  "Butterworth",
  "Gelugor",
  "George Town",
  "Gurney Drive",
  "Jelutong",
  "Juru",
  "Nibong Tebal",
  "Paya Terubong",
  "Perai",
  "Pulau Tikus",
  "Relau",
  "Sungai Ara",
  "Sungai Bakap",
  "Sungai Dua",
  "Tanjong Tokong",
  "Teluk Kumbar",
];
